-- MySQL Script generated by MySQL Workbench
-- Tue Sep 19 19:53:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aluno_online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aluno_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aluno_online` DEFAULT CHARACTER SET utf8mb4 ;
USE `aluno_online` ;

-- -----------------------------------------------------
-- Table `aluno_online`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aluno_online`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT COMMENT '1=professor\n2=aluno',
  `perfil` VARCHAR(120) NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aluno_online`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aluno_online`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `matricula` INT(11) NULL,
  `datanascimento` DATE NULL DEFAULT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `nomeresponsavel` VARCHAR(255) NULL DEFAULT NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(120) NULL,
  `ativo` INT NULL DEFAULT '1' COMMENT '1=ativo\n0=inativo',
  `idperfil` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_perfil_idx` (`idperfil` ASC) ,
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`idperfil`)
    REFERENCES `aluno_online`.`perfil` (`idperfil`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aluno_online`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aluno_online`.`curso` (
  `idcurso` INT(11) NOT NULL AUTO_INCREMENT,
  `curso` VARCHAR(255) NULL DEFAULT NULL,
  `cargahoraria` INT NULL DEFAULT NULL,
  `ativo` INT NULL DEFAULT 1 COMMENT '1=ativo\n0=inativo',
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idcurso`),
  INDEX `fk_curso_usuario1_idx` (`idusuario` ASC) ,
  CONSTRAINT `fk_curso_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `aluno_online`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aluno_online`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aluno_online`.`disciplina` (
  `id_disciplina` INT(11) NOT NULL AUTO_INCREMENT,
  `disciplina` VARCHAR(255) NULL DEFAULT NULL,
  `notas` DECIMAL(5,2) NULL DEFAULT NULL,
  `ativo` INT NULL DEFAULT 1 COMMENT '1=ativo\n0=inativo',
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_disciplina`),
  INDEX `fk_disciplina_usuario1_idx` (`idusuario` ASC) ,
  CONSTRAINT `fk_disciplina_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `aluno_online`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aluno_online`.`frequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aluno_online`.`frequencia` (
  `idfrequencia` INT NOT NULL AUTO_INCREMENT,
  `frequencia` INT NULL COMMENT '1=presente\n0=falta',
  `id_disciplina` INT(11) NOT NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idfrequencia`),
  INDEX `fk_frequencia_disciplina1_idx` (`id_disciplina` ASC) ,
  INDEX `fk_frequencia_usuario1_idx` (`idusuario` ASC) ,
  CONSTRAINT `fk_frequencia_disciplina1`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `aluno_online`.`disciplina` (`id_disciplina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_frequencia_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `aluno_online`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;